---
# file: provisioning/local.yml
- name: Nginx Playbook # タスク名
  hosts: local          # 対象ホスト 
  sudo: yes             # sudoするか
  roles:                # 実際のタスクを記述しているディレクトリ
    - nginx
  tags:                 # タスクをタグ付け
    - nginx